package cl.salcobrand.extractor.xml.faraggi.query;

public class Querys {
	
	private Querys() {
		throw new IllegalStateException("Querys class");
	}
	
	public static final String SELECT_GRAL_DATA = "SELECT a.codigo_autorizacion,\r\n"
			+ "                    a.fecha_registro,\r\n"
			+ "                    a.precio,\r\n"
			+ "                    a.cantidad,\r\n"
			+ "                    b.codigo,\r\n"
			+ "                    monto_bonificado,\r\n"
			+ "                    monto_copago,\r\n"
			+ "                    monto_deducible,\r\n"
			+ "                    monto_transaccion,\r\n"
			+ "                    a.rut_titular,\r\n"
			+ "                    NVL (e.rut, 0) rut_benef,\r\n"
			+ "                    d.rut rut_medico,\r\n"
			+ "                    d.nombres || ' ' || d.paterno || ' ' || d.materno\r\n"
			+ "                       nombre_medico,\r\n"
			+ "                    a.correlativo,\r\n"
			+ "                    b.nombre_corto nombre_producto,\r\n"
			+ "                    DECODE (b.ind_prd_generico, 'S', 'G', 'M') tipo_producto,\r\n"
			+ "                    g.atributo1,\r\n"
			+ "                    g.atributo2,\r\n"
			+ "                    g.atributo3,\r\n"
			+ "                    f.vendedor,\r\n"
			+ "                    h.direccion dir_local,\r\n"
			+ "                    a.lo_codigo,\r\n"
			+ "                    a.caja,\r\n"
			+ "                    a.nro_docto,\r\n"
			+ "                    i.folio_cliente,\r\n"
			+ "                    DECODE (i.certificacion_cliente, 'S', 1, 0)\r\n"
			+ "                       tipo_autorizacion,\r\n"
			+ "                    a.parametro_aplicacion,\r\n"
			+ "                     j.ID_WS,\r\n"
			+ "                     k.ID_SERVICIO,\r\n"
			+ "                     k.ID_SERVICIO_RESP,\r\n"
			+ "                       (select codigo\r\n"
			+ "                       from PHB.planes_texto a, PHB.clientes_web_benef b\r\n"
			+ "                       where numero_contrato = a.ct_numero_contrato\r\n"
			+ "                       and codigo < 800\r\n"
			+ "                       and a.CODIGO = b.EQUIV_CONTRATO\r\n"
			+ "                       and b.TIPO_CARGA in ('FTP', 'WS')\r\n"
			+ "                       and rownum = 1) ind_equivalencia,\r\n"
			+ "                     c.ind_webservices as ind_ws_contrato\r\n"
			+ "             FROM   PHB.detalle_consumos a,\r\n"
			+ "                    PHB.productos b,\r\n"
			+ "                    PHB.contratos c,\r\n"
			+ "                    PHB.maestro_personas d,\r\n"
			+ "                    PHB.maestro_personas e,\r\n"
			+ "                    PHB.transacciones_pos f,\r\n"
			+ "                    PHB.beneficiarios g,\r\n"
			+ "                    PHB.locales h,\r\n"
			+ "                    PHB.prefactura_cliente i,\r\n"
			+ "                     PHB.SERVICIOS_EXTERNOS j,\r\n"
			+ "                     PHB.SERVICIOS_INDWEBSERVICES k\r\n"
			+ "\r\n"
			+ "            WHERE       a.ef_codigo = 1\r\n"
			+ "                    AND a.codigo_autorizacion = 561768008\r\n"
			+ "                     and c.ind_webservices = k.IND_WEBSERVICES\r\n"
			+ "                     and k.id_servicio = j.id_servicio\r\n"
			+ "                     and k.tipo = 'CARGO'\r\n"
			+ "                    AND a.parametro_aplicacion IS NOT NULL\r\n"
			+ "                    AND a.estado_consumo IN ('1', '2')\r\n"
			+ "                    AND a.monto_bonificado + a.monto_deducible > 0\r\n"
			+ "                    AND b.inventory_item_id = a.inventory_item_id\r\n"
			+ "                    AND c.ef_codigo = a.ef_codigo\r\n"
			+ "                    AND c.numero_contrato = a.ct_numero_contrato\r\n"
			+ "                    AND c.ind_webservices = 'WS27'\r\n"
			+ "                    AND d.rut = a.rut_medico\r\n"
			+ "                    AND e.party_id = a.pt_party_id\r\n"
			+ "                    AND a.resultado_consumo IN ('00', '93')\r\n"
			+ "                    AND f.ef_codigo = a.ef_codigo\r\n"
			+ "                    AND f.codigo_autorizacion = a.codigo_autorizacion\r\n"
			+ "                    AND f.numero_linea = 0\r\n"
			+ "                    AND g.ef_codigo = a.ef_codigo\r\n"
			+ "                    AND g.ct_numero_contrato = a.ct_numero_contrato\r\n"
			+ "                    AND g.rut_titular = a.rut_titular\r\n"
			+ "                    AND g.pt_party_id = a.pt_party_id\r\n"
			+ "                    AND h.ef_codigo = 1\r\n"
			+ "                    AND h.codigo = lo_codigo\r\n"
			+ "                    AND i.codigo_autorizacion = a.codigo_autorizacion\r\n"
			+ "                    AND i.ct_numero_contrato = a.ct_numero_contrato\r\n"
			+ "         ORDER BY   a.numero_linea";
			
}
